aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
      - website/node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &deploy
    command: |
      # Deploy Jest website using Docusaurus bot
      git config --global user.email "docusaurus-bot@users.noreply.github.com"
      git config --global user.name "Website Deployment Script"
      echo "machine github.com login docusaurus-bot password $DOCUSAURUS_PUBLISH_TOKEN" > ~/.netrc
      # install Docusaurus and generate file of English strings
      yarn && cd website && yarn write-translations
      # crowdin install
      sudo apt-get update
      sudo apt-get install default-jre rsync
      wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
      sudo dpkg -i crowdin.deb
      sleep 5
      # translations upload/download
      yarn crowdin-upload
      yarn crowdin-download
      # build and publish website
      GIT_USER=docusaurus-bot USE_SSH=false yarn publish-gh-pages

version: 2
jobs:
  lint-and-typecheck:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn lint --format junit -o reports/junit/js-lint-results.xml && yarn typecheck && yarn lint-es5-build --format junit -o reports/junit/js-es5-lint-results.xml  && yarn lint:md:ci
      - store_test_results:
          path: reports/junit

  test-browser:
    working_directory: ~/jest
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn test-ci-es5-build-in-browser

  test-node-10:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run:
          command: yarn test-ci-partial
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
                path: reports/junit

  test-node-9:
    working_directory: ~/jest
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run:
          command: yarn test-ci-partial
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"


  test-jest-circus:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run:
          command: JEST_CIRCUS=1 yarn test-ci-partial
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
                path: reports/junit

  test-node-8:
    working_directory: ~/jest
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run:
          command: yarn test-ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
                path: reports/junit

  test-node-6:
    working_directory: ~/jest
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run:
          command: yarn test-ci-partial
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
                path: reports/junit

  test-and-deploy-website:
    working_directory: ~/jest
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - deploy: *deploy

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint-and-typecheck
      - test-node-8
      - test-node-6
      - test-node-10
      - test-node-9
      - test-jest-circus
      - test-browser
      - test-and-deploy-website
